require('plugin_config.hop')
require('plugin_config.lualine')
require('plugin_config.nvim-tree')
require('plugin_config.treesitter')
require('plugin_config.indent-blankline')
require('plugin_config.oxocarbon')
require('plugin_config.telescope')
