export SHELL=$(which zsh)
if [[ $(uname) == "Darwin" ]]
then
    # If you come from bash you might have to change your $PATH.
    export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH
    # use gnu core commands with their normal names
    export PATH=$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(
    aliases
    fzf
    git
    zsh-autosuggestions
    web-search
    copyfile
    dirhistory
    history
    jsontools
    z
    kubectl
    you-should-use
    # plugins for macos:
    macos 
)

source $ZSH/oh-my-zsh.sh
export FZF_DEFAULT_OPTS='
  --multi
  --height=50%
  --margin=1%,1%,1%,1%
  --layout=reverse-list
  --border=rounded
  --info=inline
  --prompt="$>"
  --pointer="→"
  --marker="♡"
  --header="CTRL-c or ESC to quit"
  --color="dark,fg:magenta"
  --ansi
  --preview "bat --style=numbers --color=always {}"
  --preview-window "right:60%,wrap"
'

export FZF_CTRL_T_COMMAND='find . -type f -not -path "*/\.git/*"'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# user defined aliases
alias cc='claude'
alias ls='eza';
alias nv='nvim'
alias gch='git checkout'
alias gdn='git difftool --tool=nvimdiff'
alias kct='kubectl ctx'
alias kns='kubectl ns'
alias lg='lazygit'
alias bat='bat --theme="base16"'
go() {
    if [ $# -gt 0 ] && [ "$1" = "doc" ]; then
        shift
        command go doc $@ | bat -l go --style=plain 
    else
        command go "$@"
    fi
}

# Local bin setup
export PATH=$HOME/.local/bin:$PATH

# Go setup
export PATH=/usr/local/go/bin:$PATH
export PATH=$HOME/go/bin:$PATH

# Rust setup
export PATH=$HOME/.cargo/bin:$PATH

# kubectl shortcuts
# source $HOME/.config/zsh/kubectl_alias.sh

export PATH=/usr/local/nvim/bin/:$PATH

export EDITOR=nvim

# krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# fzf git setup
source ~/.config/fzf-git.sh

# fzf git branch checkout
#
fzf-git-branch() {
    git rev-parse HEAD > /dev/null 2>&1 || return

    git branch --color=always --all --sort=-committerdate |
        grep -v HEAD |
        fzf --height 50% --ansi --no-multi --preview-window right:65% \
            --preview 'git log -n 50 --color=always --date=short --pretty="format:%C(auto)%cd %h%d %s" $(sed "s/.* //" <<< {})' |
        sed "s/.* //"
}


fzf-git-checkout() {
    git rev-parse HEAD > /dev/null 2>&1 || return

    local branch

    branch=$(fzf-git-branch)
    if [[ "$branch" = "" ]]; then
        echo "No branch selected."
        return
    fi

    # If branch name starts with 'remotes/' then it is a remote branch. By
    # using --track and a remote branch name, it is the same as:
    # git checkout -b branchName --track origin/branchName
    if [[ "$branch" = 'remotes/'* ]]; then
        git checkout --track $branch
    else
        git checkout $branch;
    fi
}
alias gco='fzf-git-checkout'

autoload -U compinit && compinit

[[ -s "/Users/charlesz/.gvm/scripts/gvm" ]] && source "/Users/charlesz/.gvm/scripts/gvm"

# load the openai api key if exist
# [[ -f ~/.openai_api_key ]] && export OPENAI_API_KEY=$(<~/.openai_api_key)

# export PATH=$HOME/Works/ai-tools/bin:$PATH
[ -f $HOME/.sbn_aliases ] && source $HOME/.sbn_aliases

# init the starship
eval "$(starship init zsh)"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
